Add triage info for rancher/rancher images
rancher/image-scanning pull request #53
Opened 2021-08-03 07:53 UTC by brendarearden

Add waiting notes for rancher/rancher images. 

Removed quotes from previous istio image notes for consistency.

2021-08-03 21:48 UTC, cbron requested changes

2021-08-03 21:48 UTC, cbron commented on docs/_data/cves-v2.6.csv
> +rancher/istio-installer:1.10.2-rancher1,github.com/docker/distribution,alpine,CVE-2017-11468,HIGH,https://avd.aquasec.com/nvd/cve-2017-11468,v2.7.0-rc.0+incompatible,,waiting,"Upstream Issue: https:/
Should this be in ignore or waiting ? I don't see in that issue that it doesn't impact istio, does it ? If so then: 
```suggestion
rancher/istio-installer:1.10.2-rancher1,github.com/docker/distribution,alpine,CVE-2017-11468,HIGH,https://avd.aquasec.com/nvd/cve-2017-11468,v2.7.0-rc.0+incompatible,,waiting,"This CVE does not impact istio's security: https://github.com/istio/istio/issues/34179."

```

2021-08-03 21:48 UTC, cbron commented on docs/_data/cves-v2.6.csv
> +rancher/istio-installer:1.10.2-rancher1,github.com/ulikunitz/xz,alpine,CVE-2021-29482,HIGH,https://avd.aquasec.com/nvd/cve-2021-29482,v0.5.8,,waiting,"Issue: https://github.com/rancher/rancher/issues
Waiting should only be used for upstream blockers, just leave state empty. For note put "Tracked in:" or "Issue:"

2021-08-03 21:48 UTC, cbron commented on docs/_data/cves-v2.6.csv
> -rancher/mirrored-istio-install-cni:1.10.2,libsystemd0,ubuntu,CVE-2021-33910,HIGH,https://avd.aquasec.com/nvd/cve-2021-33910,237-3ubuntu10.49,,waiting," ""Issue: https://github.com/rancher/rancher/iss
Same here and below, since 1.10.2 is out then we aren't blocked, and shouldn't be in waiting. Note is fine.

2021-08-04 02:02 UTC, rmweir requested changes
Can approve/merge once @cbron feedback has been addressed.

2021-08-04 15:16 UTC, cbron commented on docs/_data/cves-v2.6.csv
> +rancher/istio-installer:1.10.2-rancher1,github.com/docker/distribution,alpine,CVE-2017-11468,HIGH,https://avd.aquasec.com/nvd/cve-2017-11468,v2.7.0-rc.0+incompatible,,waiting,This CVE does not impact
Still confused why we say it doesn't impact security when the issue has no context

2021-08-04 15:16 UTC, cbron commented on docs/_data/cves-v2.6.csv
> +rancher/rancher:master-head,github.com/docker/distribution,suse linux enterprise server,CVE-2017-11468,HIGH,https://avd.aquasec.com/nvd/cve-2017-11468,v2.7.0-rc.0+incompatible,,waiting,"Waiting on up
This one needs tracking issue so it matches two lines below it.

2021-08-04 17:17 UTC, cbron commented on docs/_data/cves-v2.6.csv
> +rancher/istio-installer:1.10.2-rancher1,github.com/docker/distribution,alpine,CVE-2017-11468,HIGH,https://avd.aquasec.com/nvd/cve-2017-11468,v2.7.0-rc.0+incompatible,,waiting,This CVE does not impact
For future reference we talked with them separately and confirmed this.

2021-08-04 17:18 UTC, cbron approved these changes

2021-08-05 00:16 UTC, merged